apiVersion: v1
kind: Service
metadata:
  name: weatherapp-auth
spec:
  selector:
    app.kubernetes.io/name: weatherapp-auth
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP