apiVersion: v1
kind: Service
metadata:
  name: weatherapp-weather
spec:
  selector:
    app.kubernetes.io/name: weatherapp-weather
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: http
  type: ClusterIP